### ISSUE TITLE
Static gun porting List

### ISSUE THREAD

**Issue by ComfyPillow** [fparma/fp-static-weapons#1]
Checklist of weapons being ported over from the RDS Static Weapon pack.
These are all the static weapons which are currently available in some form in the RDS Static Weapon pack. Each one of those will be ported individually and will be independent of each other.
- [x] AGS-30
- [x] 122-mm howitzer D-30
- [x] DShKM
- [x] 9K38 Igla
- [x] Kord 6P50
- [x] M2 Browning
- [x] M119 howitzer
- [x] M252 81mm Mortar
- [x] 9K115-2 Metis-M
- [x] Mk 19 grenade launcher
- [x] 2B14 Podnos
- [x] SPG-9
- [x] BGM-71 TOW
- [x]  ZU-23-2 "Sergey"

**Comment by Mallow234** [comment]
You might be able to add the tow variants ( baseline, i-tow, 2, 2a)

**Comment by ComfyPillow** [comment]
Different variants are indeed a possibility. I'm first focusing on bringing back the base content of RDS, refine it and then I'll look at providing different variants of the static weapons.

If you could open an issue with a list of variation of different weapons, and maybe a reference to them (Wikipedia or similar, outlining the changes/improvements), that would be most helpful.

**Comment by ComfyPillow** [comment]
All Weapons have been ported. Some still in basic form. Moving on to refine them.
