### ISSUE TITLE
Port back the Assemble Backpack functionality for Applicable Weapons.

### ISSUE THREAD

**Issue by ComfyPillow** [fparma/fp-static-weapons#11]
Static Weapons for which this should be available are the following:
- [x] ags30
- [x] dshkm
- [x] kord
- [x] m2
- [x] m252
- [x] metis
- [x] mk19
- [x] podnos
- [x] searchlight
- [x] spg9

**Comment by ComfyPillow** [comment]
Look into providing a generic Tripod Item, which can be used across all of the FP Static Assembly compatible weapons.

This should keep things relatively simple and doesen't clutter the Virtual Arsenal as much.

**Comment by Cuel** [comment]
Can't use the vanilla tripod?

**Comment by ComfyPillow** [comment]
Haven't looked into how the bag assembly works, but yeah I'm considering using the Vanilla Bipod if possible.

**Comment by ComfyPillow** [comment]
From what I've seen, Arma has 1 Tripod for each kind of Static weapon.

For example, NATO HMG, CSAT HMG and AAF HMG each have their own tripods.

```
B_HMG_01_support_F
O_HMG_01_support_F
I_HMG_01_support_F
```

And from what I've seen, Both Parts of the Weapon, the Weapon Bag and the tripod bag needs to know it's counterpart and to which vehicle it assembles to.

So from what I've seen in the BI config and the RDS Bag Config, each static weapon needs it's own bipod and gun.

**Comment by Kauwgompje** [comment]
The Podnos and M252 both have the assemble backpack functionality, names on the backpack are from the M6 mortar though.
(yesterdays build)

**Comment by ComfyPillow** [comment]
M252 and Podnos inherit from the MK6, in order to be fully compatible with ACE Mortars.
That means, as of right now, they use the assemblyinfo entry from the MK6.

Will be fixed with the others once I get to create all the bag configs.

**Comment by ComfyPillow** [comment]
All of those now have compatible Bag Assembly.
