### ISSUE TITLE
Increase Dispersion of the DshKM

### ISSUE THREAD

**Issue by ComfyPillow** [fparma/fp-static-weapons#23]
The DshKM is currently almost pinpoint accurate over 1KM and beyond.
The config needs to be adjusted to make the gun more inaccurate over distances beyond ~400-600m.

**Comment by Kauwgompje** [comment]
KORD has the same stats iirc

**Comment by Kauwgompje** [comment]
KORD is actually twice as accurate as DShKM in its current state

**Comment by ComfyPillow** [comment]
I did some checks and aparently the Vanilla Static HMG has a Dispersion of 0.002. The Kord has a dispersion of 0.00085 and the Dshkm has a dispersion of 0.0015.

So as of right now, the DshKM is more accurate than the Vanilla Future-Like HMG.

I wanna test out how the weapons feel when I use 0.003 for the Kord, and 0.006 for the DshKM, and work my way up from there.

**Comment by ComfyPillow** [comment]
Done. Looks good
