### ISSUE TITLE
Kord Regular and Kord Tripod variants share the same name

### ISSUE THREAD

**Issue by ComfyPillow** [fparma/fp-static-weapons#25]
When trying out the dispersino changes, I noticed this:

https://github.com/fparma/fp_static_weapons/blame/master/src/kord/includes/CfgVehicles.hpp#L9
https://github.com/fparma/fp_static_weapons/blame/master/src/kord/includes/CfgVehicles.hpp#L73

@Kauwgompje 
Might wanna adjust the names of the weapons to see which one is which, without having to place them down first and see what they look like.

**Comment by Kauwgompje** [comment]
This was an oversight when I was pasting the names, will fix when #26 is decided upon.

**Comment by ComfyPillow** [comment]
Fixed with new Name
