### ISSUE TITLE
M2 Browning reload sound spazzing.

### ISSUE THREAD

**Issue by ComfyPillow** [fparma/fp-static-weapons#3]
**Mods:**
- `@CBA_A3`
- `@fp_static_weapons`

**Description:**
- When the M2 Browning has to reload, it's reload sound spazzes out at the beginning, and after the reload is done, the full reload sound plays normally.

**Steps to reproduce:**
- Place down Object 'fp_static_m2_b' and fire until reload. Then Observe reload sound.

**Where did the issue occur?**
- Editor

**Comment by Cuel** [comment]
and the sound is ok when played?

**Comment by ComfyPillow** [comment]
In the filesystem, yes.
What I'm wondering about is that there's an reloadMagazineSound config entry inside the CfgVehicles config. To my knowledge and the CfgVehicles reference, that souldn't be there. This may be an error from the RDS Static Weapons pack. I'm gonna have to see if I can reduce it with RDS, otherwise it's something on my side.

Then again, since the M2 is using the Vanilla HMG_M2 Weapon, it should just carry the correct settings over automatically, so I don't exactly know whats happening. Maybe reloadMagazineSound from CfgVehicles is interferring with the reload of the HMG_M2 Weapon, but I find that kinda unlikely.

``` c++
reloadMagazineSound[]={"\FP_Static_Weapons\m2\data\reload-belt-1",db-25,1,40};
```

https://github.com/fparma/fp-static-weapons/blob/master/src/m2/includes/CfgVehicles.hpp#L9

Once I get home to and have access to Arma 3 again, I'll try testing without these config entries and see if it makes a difference.

**Comment by Mallow234** [comment]
Afaik this also occurs with the current rhs m2, so you might be able to take a look there

**Comment by ComfyPillow** [comment]
Looks like both RHS and RDS also suffer from the same issue. I'll mark this as a BI Issue for the time being, and look into how RHS will fix this (I hope they do).

Worth noting is that FP's M2 is a lot less bugged compared to RHS's M2 ;)

https://www.youtube.com/watch?v=I82nlPW9EZc

**Comment by ComfyPillow** [comment]
Related RHS Issue:
http://feedback.rhsmods.org/view.php?id=1229

Related BI Feedback Issues:
http://feedback.arma3.com/view.php?id=25678
http://feedback.arma3.com/view.php?id=26016

Issue resolves itself once BI fixes it.

**Comment by ComfyPillow** [comment]
Issue got fixed by BI
