### ISSUE TITLE
Replace Nunjucks Templating with A3 C++ Preprocessor + CBA Macros

### ISSUE THREAD

**Issue by ComfyPillow** [fparma/fp-static-weapons#8]
Since we need to binarize this addon at one point, it would simpify the workflow a lot.

Basically copy the behavior and ideally port the make.py script from ACE3 over to this addon.

**Comment by ComfyPillow** [comment]
ACE uses Mikero's PBO Tools to Binarize the PBO Files.
https://dev.withsix.com/projects/mikero-pbodll/files

Line for Executing pboProject in ACE's Build System:
https://github.com/acemod/ACE3/blob/master/tools/make.py#L1219-L1223

**Comment by ComfyPillow** [comment]
Binarizing the Project with PBOProject now works properly without errors since Commit https://github.com/fparma/fp_static_weapons/commit/8526dc8aa071808fac5feaf284dcdd58c06e31d2

Also Investigate if makepbo is worth using. (Additional Linters which would aid in finding problems)

**Comment by Cuel** [comment]
makepbo doesn't binarize, but checks for errors and other problems that BI tools doesn't
if you need to binarize, it's recommended to run "makepbo -Q foldername" before running BI tools

**Comment by ComfyPillow** [comment]
Good to know. I'll keep this in mind.

**Comment by ComfyPillow** [comment]
Nunjucks and all NodeJS Dependencies have been completely replaced in favor of the regular BI PreProcessor and Binarizing.
